### ISSUE TITLE
Hardcoded gitlab.com domain

### ISSUE THREAD

**Issue by kemko** [avtar/push-ref-gitlab#1]
Hello.

It seems that in [index.js#L180](https://github.com/avtar/push-ref-gitlab/blob/119746c6bee533d8012e7c1e194d07691dea2c7d/index.js#L180) hardcoded `gitlab.com` domain instead of `GITLAB_HOST`.

**Comment by avtar** [comment]
Thanks for catching that 🤝 The hardcoded domain has been removed.
